image: node:16.14.2

clone:
  depth: full

definitions:
  steps:
    - step: &flow
        name: Run flow
        script:
          - pipe: docker://atlassian/artifactory-sidekick:latest
          - . .artifactory/activate.sh
          - yarn install --frozen-lockfile
          - yarn run flow check
    - step: &typescript
        name: Run TypeScript
        script:
          - pipe: docker://atlassian/artifactory-sidekick:latest
          - . .artifactory/activate.sh
          - yarn install --frozen-lockfile
          - yarn build
          - yarn run build-ts
    - step: &lint
        name: Run lint
        script:
          - pipe: docker://atlassian/artifactory-sidekick:latest
          - . .artifactory/activate.sh
          - yarn install --frozen-lockfile
          - yarn run lint
          - npx prettier "./packages/*/*/pkg/**/*.{js,json,md}" --list-different --no-error-on-unmatched-pattern
    - step: &test-unit
        name: Run unit tests
        size: 2x
        script:
          - pipe: docker://atlassian/artifactory-sidekick:latest
          - . .artifactory/activate.sh
          - yarn install --frozen-lockfile
          - yarn run test:unit
    - step: &test-integration
        name: Run integration tests
        size: 2x
        script:
          - pipe: docker://atlassian/artifactory-sidekick:latest
          - . .artifactory/activate.sh
          - yarn install --frozen-lockfile
          - yarn build
          - yarn run test:integration-ci
    - step: &build-release-parcel
        name: Build and Release Parcel
        script:
          - pipe: docker://atlassian/artifactory-sidekick:latest
          - . .artifactory/activate.sh
          - npm set unsafe-perm true
          - yarn install --frozen-lockfile
          - yarn lerna publish from-git --no-push --yes --registry https://packages.atlassian.com/api/npm/atlassian-npm/
    - step: &validate-docs
        name: Validate Atlassian Docs
        image: node:12-slim
        caches:
          - node
        script:
          - pipe: docker://atlassian/artifactory-sidekick:latest
          - source .artifactory/activate.sh
          - cd dac
          - yarn
          - yarn validate
          - yarn link-check
    - step: &release-docs
        name: Release Atlassian Docs
        image: node:12-slim
        caches:
          - node
        script:
          - pipe: docker://atlassian/artifactory-sidekick:latest
          - source .artifactory/activate.sh
          - cd dac
          - yarn
          # Set the release version of the package to be the same as the build number.
          - npm version "1.${BITBUCKET_BUILD_NUMBER}.0" -m "%s [skip ci]"
          - yarn validate
          - yarn publish

pipelines:
  default:
    - parallel:
        - step: *flow
        - step: *typescript
        - step: *lint
        - step: *test-unit
        - step: *test-integration
        - step: *validate-docs
  tags:
    '*':
      - parallel:
          - step: *flow
          - step: *typescript
          - step: *lint
          - step: *test-unit
          - step: *test-integration
          - step: *validate-docs
      - step: *build-release-parcel
      - step: *release-docs
  custom:
    release-docs:
      - step: *validate-docs
      - step: *release-docs
