[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel-js-swc-napi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = {version =  "2.10.6", features = ["napi4", "compat-mode", "serde-json"]}
napi-derive = "2.9.4"
parcel-js-swc-core = { path = "../core" }

[target.'cfg(target_os = "macos")'.dependencies]
jemallocator = { version = "0.3.2", features = ["disable_initial_exec_tls"] }

[target.'cfg(windows)'.dependencies]
mimalloc = { version = "0.1.25", default-features = false }

[build-dependencies]
napi-build = "2"
