[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel-hash"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "2.12.6"
napi-derive = "2.12.5"
xxhash-rust = { version = "0.8.2", features = ["xxh3"] }

[build-dependencies]
napi-build = "2"
